services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-app
    volumes:
      - pgdata:/var/lib/postgresql/data

  embed-api:
    build: ./embed-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - HOST=0.0.0.0
      - PORT=8000

volumes:
  pgdata:
